
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('Inventory').del()
    .then(function () {
      // Inserts seed entries
      return knex('Inventory').insert(
        [{ "name": "suspendisse potenti" },
        { "name": "lorem quisque" },
        { "name": "massa quis" },
        { "name": "phasellus sit" },
        { "name": "quisque" },
        { "name": "ut ultrices" },
        { "name": "nisl nunc" },
        { "name": "sem" },
        { "name": "vitae" },
        { "name": "rutrum ac" },
        { "name": "natoque" },
        { "name": "sit" },
        { "name": "turpis enim" },
        { "name": "molestie" },
        { "name": "ac nibh" },
        { "name": "nonummy integer" },
        { "name": "sapien" },
        { "name": "in" },
        { "name": "tempus vel" },
        { "name": "in congue" },
        { "name": "id ligula" },
        { "name": "ligula in" },
        { "name": "sapien" },
        { "name": "vivamus tortor" },
        { "name": "aliquam" },
        { "name": "sociis" },
        { "name": "vivamus in" },
        { "name": "dui" },
        { "name": "non mauris" },
        { "name": "nullam" },
        { "name": "euismod" },
        { "name": "pellentesque" },
        { "name": "platea" },
        { "name": "porta volutpat" },
        { "name": "vestibulum ac" },
        { "name": "aliquet" },
        { "name": "augue" },
        { "name": "felis" },
        { "name": "id" },
        { "name": "sed interdum" },
        { "name": "mattis odio" },
        { "name": "tincidunt in" },
        { "name": "commodo" },
        { "name": "ut odio" },
        { "name": "habitasse" },
        { "name": "id" },
        { "name": "leo" },
        { "name": "adipiscing" },
        { "name": "at" },
        { "name": "donec vitae" },
        { "name": "interdum" },
        { "name": "pulvinar lobortis" },
        { "name": "nisl" },
        { "name": "duis" },
        { "name": "nulla ultrices" },
        { "name": "integer pede" },
        { "name": "vel" },
        { "name": "orci nullam" },
        { "name": "porttitor lorem" },
        { "name": "nibh" },
        { "name": "semper est" },
        { "name": "eleifend" },
        { "name": "nulla elit" },
        { "name": "ac enim" },
        { "name": "consequat" },
        { "name": "nullam" },
        { "name": "morbi vestibulum" },
        { "name": "sociis natoque" },
        { "name": "consequat" },
        { "name": "primis" },
        { "name": "semper rutrum" },
        { "name": "lacus morbi" },
        { "name": "luctus" },
        { "name": "ultrices" },
        { "name": "hendrerit at" },
        { "name": "convallis nulla" },
        { "name": "potenti" },
        { "name": "platea dictumst" },
        { "name": "vestibulum ante" },
        { "name": "cursus" },
        { "name": "imperdiet nullam" },
        { "name": "lacus purus" },
        { "name": "consequat" },
        { "name": "elit" },
        { "name": "nec" },
        { "name": "lectus" },
        { "name": "sed tincidunt" },
        { "name": "id" },
        { "name": "ultrices libero" },
        { "name": "amet" },
        { "name": "libero convallis" },
        { "name": "elementum" },
        { "name": "gravida" },
        { "name": "cubilia" },
        { "name": "quam" },
        { "name": "lectus" },
        { "name": "velit vivamus" },
        { "name": "id ligula" },
        { "name": "ultrices posuere" },
        { "name": "libero" }]
      );
    });
};
