
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('Store').del()
    .then(function () {
      // Inserts seed entries
      return knex('Store').insert(
        [{ "locationID": 7, "stockInventoryID": 69, "name": "dictumst aliquam" },
        { "locationID": 9, "stockInventoryID": 41, "name": "risus praesent" },
        { "locationID": 16, "stockInventoryID": 81, "name": "donec" },
        { "locationID": 10, "stockInventoryID": 66, "name": "congue etiam" },
        { "locationID": 15, "stockInventoryID": 33, "name": "aliquam" },
        { "locationID": 22, "stockInventoryID": 16, "name": "augue" },
        { "locationID": 20, "stockInventoryID": 27, "name": "sapien" },
        { "locationID": 17, "stockInventoryID": 84, "name": "accumsan" },
        { "locationID": 17, "stockInventoryID": 55, "name": "est donec" },
        { "locationID": 10, "stockInventoryID": 13, "name": "morbi" },
        { "locationID": 25, "stockInventoryID": 59, "name": "ut suscipit" },
        { "locationID": 3, "stockInventoryID": 67, "name": "non" },
        { "locationID": 9, "stockInventoryID": 70, "name": "mi integer" },
        { "locationID": 13, "stockInventoryID": 37, "name": "sociis" },
        { "locationID": 9, "stockInventoryID": 90, "name": "pulvinar nulla" },
        { "locationID": 11, "stockInventoryID": 3, "name": "congue risus" },
        { "locationID": 7, "stockInventoryID": 36, "name": "pharetra" },
        { "locationID": 21, "stockInventoryID": 80, "name": "non" },
        { "locationID": 17, "stockInventoryID": 61, "name": "porttitor pede" },
        { "locationID": 22, "stockInventoryID": 21, "name": "pretium iaculis" },
        { "locationID": 12, "stockInventoryID": 82, "name": "cursus urna" },
        { "locationID": 22, "stockInventoryID": 54, "name": "in" },
        { "locationID": 16, "stockInventoryID": 48, "name": "aenean" },
        { "locationID": 26, "stockInventoryID": 58, "name": "rhoncus mauris" },
        { "locationID": 13, "stockInventoryID": 90, "name": "ipsum dolor" },
        { "locationID": 25, "stockInventoryID": 29, "name": "at" },
        { "locationID": 18, "stockInventoryID": 35, "name": "vulputate justo" },
        { "locationID": 15, "stockInventoryID": 46, "name": "quisque porta" },
        { "locationID": 15, "stockInventoryID": 62, "name": "tellus" },
        { "locationID": 15, "stockInventoryID": 6, "name": "erat" },
        { "locationID": 5, "stockInventoryID": 59, "name": "vestibulum ante" },
        { "locationID": 11, "stockInventoryID": 23, "name": "urna ut" },
        { "locationID": 24, "stockInventoryID": 94, "name": "interdum in" },
        { "locationID": 10, "stockInventoryID": 47, "name": "in congue" },
        { "locationID": 9, "stockInventoryID": 92, "name": "nisi" },
        { "locationID": 27, "stockInventoryID": 28, "name": "amet" },
        { "locationID": 27, "stockInventoryID": 71, "name": "platea dictumst" },
        { "locationID": 22, "stockInventoryID": 59, "name": "turpis" },
        { "locationID": 7, "stockInventoryID": 77, "name": "habitasse" },
        { "locationID": 16, "stockInventoryID": 64, "name": "dapibus duis" },
        { "locationID": 22, "stockInventoryID": 98, "name": "amet eleifend" },
        { "locationID": 6, "stockInventoryID": 43, "name": "donec ut" },
        { "locationID": 23, "stockInventoryID": 65, "name": "eget nunc" },
        { "locationID": 2, "stockInventoryID": 100, "name": "platea" },
        { "locationID": 25, "stockInventoryID": 69, "name": "sit amet" },
        { "locationID": 8, "stockInventoryID": 2, "name": "est phasellus" },
        { "locationID": 19, "stockInventoryID": 66, "name": "leo pellentesque" },
        { "locationID": 22, "stockInventoryID": 85, "name": "et" },
        { "locationID": 6, "stockInventoryID": 18, "name": "elementum" },
        { "locationID": 3, "stockInventoryID": 86, "name": "ipsum" },
        { "locationID": 16, "stockInventoryID": 99, "name": "eu" },
        { "locationID": 18, "stockInventoryID": 7, "name": "leo" },
        { "locationID": 21, "stockInventoryID": 31, "name": "enim lorem" },
        { "locationID": 1, "stockInventoryID": 62, "name": "quis" },
        { "locationID": 25, "stockInventoryID": 67, "name": "eget eros" },
        { "locationID": 9, "stockInventoryID": 34, "name": "euismod scelerisque" },
        { "locationID": 3, "stockInventoryID": 40, "name": "gravida nisi" },
        { "locationID": 11, "stockInventoryID": 6, "name": "nulla" },
        { "locationID": 26, "stockInventoryID": 83, "name": "in hac" },
        { "locationID": 23, "stockInventoryID": 86, "name": "sodales sed" },
        { "locationID": 3, "stockInventoryID": 42, "name": "mus etiam" },
        { "locationID": 21, "stockInventoryID": 85, "name": "sollicitudin vitae" },
        { "locationID": 21, "stockInventoryID": 7, "name": "sit" },
        { "locationID": 26, "stockInventoryID": 65, "name": "rutrum neque" },
        { "locationID": 22, "stockInventoryID": 25, "name": "lacus" },
        { "locationID": 2, "stockInventoryID": 57, "name": "quis turpis" },
        { "locationID": 9, "stockInventoryID": 50, "name": "pellentesque ultrices" },
        { "locationID": 26, "stockInventoryID": 13, "name": "orci" },
        { "locationID": 2, "stockInventoryID": 5, "name": "sed sagittis" },
        { "locationID": 26, "stockInventoryID": 64, "name": "lacus at" },
        { "locationID": 21, "stockInventoryID": 81, "name": "semper rutrum" },
        { "locationID": 23, "stockInventoryID": 26, "name": "porttitor lorem" },
        { "locationID": 13, "stockInventoryID": 44, "name": "blandit mi" },
        { "locationID": 4, "stockInventoryID": 95, "name": "mollis molestie" },
        { "locationID": 17, "stockInventoryID": 49, "name": "at ipsum" },
        { "locationID": 20, "stockInventoryID": 12, "name": "velit" },
        { "locationID": 4, "stockInventoryID": 70, "name": "nam ultrices" },
        { "locationID": 17, "stockInventoryID": 44, "name": "tempus" },
        { "locationID": 10, "stockInventoryID": 89, "name": "eu" },
        { "locationID": 25, "stockInventoryID": 36, "name": "nec" },
        { "locationID": 16, "stockInventoryID": 45, "name": "ultrices" },
        { "locationID": 14, "stockInventoryID": 85, "name": "erat" },
        { "locationID": 4, "stockInventoryID": 20, "name": "blandit mi" },
        { "locationID": 16, "stockInventoryID": 63, "name": "justo lacinia" },
        { "locationID": 13, "stockInventoryID": 5, "name": "aliquet massa" },
        { "locationID": 26, "stockInventoryID": 3, "name": "nunc" },
        { "locationID": 26, "stockInventoryID": 20, "name": "sapien" },
        { "locationID": 1, "stockInventoryID": 80, "name": "amet sem" },
        { "locationID": 20, "stockInventoryID": 10, "name": "orci eget" },
        { "locationID": 27, "stockInventoryID": 31, "name": "at" },
        { "locationID": 4, "stockInventoryID": 87, "name": "semper" },
        { "locationID": 5, "stockInventoryID": 36, "name": "scelerisque" },
        { "locationID": 3, "stockInventoryID": 8, "name": "nam" },
        { "locationID": 11, "stockInventoryID": 93, "name": "tempor" },
        { "locationID": 11, "stockInventoryID": 7, "name": "ipsum primis" },
        { "locationID": 1, "stockInventoryID": 34, "name": "vivamus metus" },
        { "locationID": 14, "stockInventoryID": 40, "name": "tincidunt" },
        { "locationID": 27, "stockInventoryID": 13, "name": "aliquam" },
        { "locationID": 4, "stockInventoryID": 6, "name": "cras mi" },
        { "locationID": 20, "stockInventoryID": 99, "name": "metus arcu" },
        { "locationID": 17, "stockInventoryID": 52, "name": "pede" },
        { "locationID": 12, "stockInventoryID": 20, "name": "viverra" },
        { "locationID": 15, "stockInventoryID": 87, "name": "consequat" },
        { "locationID": 7, "stockInventoryID": 18, "name": "amet eleifend" },
        { "locationID": 21, "stockInventoryID": 83, "name": "lorem id" },
        { "locationID": 26, "stockInventoryID": 99, "name": "turpis sed" },
        { "locationID": 10, "stockInventoryID": 60, "name": "neque" },
        { "locationID": 6, "stockInventoryID": 88, "name": "dui nec" },
        { "locationID": 9, "stockInventoryID": 78, "name": "odio" },
        { "locationID": 13, "stockInventoryID": 56, "name": "nam" },
        { "locationID": 7, "stockInventoryID": 29, "name": "justo" },
        { "locationID": 13, "stockInventoryID": 100, "name": "praesent blandit" },
        { "locationID": 24, "stockInventoryID": 65, "name": "sapien cum" },
        { "locationID": 16, "stockInventoryID": 77, "name": "habitasse" },
        { "locationID": 27, "stockInventoryID": 46, "name": "rutrum" },
        { "locationID": 20, "stockInventoryID": 22, "name": "vulputate vitae" },
        { "locationID": 20, "stockInventoryID": 90, "name": "quis turpis" },
        { "locationID": 4, "stockInventoryID": 15, "name": "dolor" },
        { "locationID": 18, "stockInventoryID": 62, "name": "in leo" },
        { "locationID": 16, "stockInventoryID": 8, "name": "nam" },
        { "locationID": 19, "stockInventoryID": 22, "name": "vestibulum vestibulum" },
        { "locationID": 5, "stockInventoryID": 99, "name": "justo" },
        { "locationID": 13, "stockInventoryID": 30, "name": "in" },
        { "locationID": 25, "stockInventoryID": 95, "name": "eu tincidunt" },
        { "locationID": 27, "stockInventoryID": 16, "name": "in est" },
        { "locationID": 18, "stockInventoryID": 97, "name": "donec posuere" },
        { "locationID": 8, "stockInventoryID": 60, "name": "massa volutpat" },
        { "locationID": 4, "stockInventoryID": 29, "name": "aenean" },
        { "locationID": 14, "stockInventoryID": 26, "name": "sapien in" },
        { "locationID": 19, "stockInventoryID": 28, "name": "donec" },
        { "locationID": 22, "stockInventoryID": 75, "name": "nam nulla" },
        { "locationID": 16, "stockInventoryID": 55, "name": "tincidunt" },
        { "locationID": 4, "stockInventoryID": 91, "name": "elementum pellentesque" },
        { "locationID": 22, "stockInventoryID": 97, "name": "ultrices mattis" },
        { "locationID": 26, "stockInventoryID": 12, "name": "ultrices" },
        { "locationID": 11, "stockInventoryID": 3, "name": "quam" },
        { "locationID": 12, "stockInventoryID": 90, "name": "potenti nullam" },
        { "locationID": 23, "stockInventoryID": 88, "name": "nec" },
        { "locationID": 2, "stockInventoryID": 67, "name": "orci luctus" },
        { "locationID": 24, "stockInventoryID": 95, "name": "adipiscing" },
        { "locationID": 6, "stockInventoryID": 43, "name": "morbi non" },
        { "locationID": 6, "stockInventoryID": 83, "name": "vitae" },
        { "locationID": 22, "stockInventoryID": 20, "name": "semper est" },
        { "locationID": 17, "stockInventoryID": 24, "name": "integer" },
        { "locationID": 13, "stockInventoryID": 20, "name": "suspendisse potenti" },
        { "locationID": 18, "stockInventoryID": 34, "name": "aliquam" },
        { "locationID": 7, "stockInventoryID": 19, "name": "vulputate" },
        { "locationID": 15, "stockInventoryID": 99, "name": "porttitor" },
        { "locationID": 23, "stockInventoryID": 72, "name": "tincidunt" },
        { "locationID": 23, "stockInventoryID": 97, "name": "placerat" },
        { "locationID": 14, "stockInventoryID": 48, "name": "sit" },
        { "locationID": 12, "stockInventoryID": 88, "name": "sed vestibulum" },
        { "locationID": 17, "stockInventoryID": 59, "name": "felis" },
        { "locationID": 22, "stockInventoryID": 41, "name": "pretium iaculis" },
        { "locationID": 23, "stockInventoryID": 81, "name": "ipsum" },
        { "locationID": 10, "stockInventoryID": 79, "name": "et" },
        { "locationID": 6, "stockInventoryID": 46, "name": "libero nullam" },
        { "locationID": 7, "stockInventoryID": 15, "name": "donec" },
        { "locationID": 4, "stockInventoryID": 64, "name": "pede malesuada" },
        { "locationID": 24, "stockInventoryID": 33, "name": "semper" },
        { "locationID": 26, "stockInventoryID": 53, "name": "tempor" },
        { "locationID": 22, "stockInventoryID": 65, "name": "vel" },
        { "locationID": 23, "stockInventoryID": 30, "name": "felis" },
        { "locationID": 7, "stockInventoryID": 10, "name": "cras" },
        { "locationID": 16, "stockInventoryID": 53, "name": "nunc" },
        { "locationID": 6, "stockInventoryID": 92, "name": "nulla quisque" },
        { "locationID": 23, "stockInventoryID": 66, "name": "luctus et" },
        { "locationID": 4, "stockInventoryID": 19, "name": "justo" },
        { "locationID": 2, "stockInventoryID": 2, "name": "curabitur" },
        { "locationID": 11, "stockInventoryID": 60, "name": "aliquet" },
        { "locationID": 15, "stockInventoryID": 83, "name": "luctus" },
        { "locationID": 22, "stockInventoryID": 41, "name": "varius ut" },
        { "locationID": 18, "stockInventoryID": 52, "name": "id" },
        { "locationID": 17, "stockInventoryID": 68, "name": "quam sollicitudin" },
        { "locationID": 21, "stockInventoryID": 41, "name": "elementum" },
        { "locationID": 21, "stockInventoryID": 29, "name": "posuere cubilia" },
        { "locationID": 9, "stockInventoryID": 66, "name": "eros" },
        { "locationID": 1, "stockInventoryID": 38, "name": "libero rutrum" },
        { "locationID": 6, "stockInventoryID": 6, "name": "sit amet" },
        { "locationID": 26, "stockInventoryID": 56, "name": "placerat" },
        { "locationID": 7, "stockInventoryID": 28, "name": "varius" },
        { "locationID": 8, "stockInventoryID": 42, "name": "posuere" },
        { "locationID": 21, "stockInventoryID": 84, "name": "eget" },
        { "locationID": 8, "stockInventoryID": 16, "name": "sapien sapien" },
        { "locationID": 14, "stockInventoryID": 35, "name": "quis augue" },
        { "locationID": 7, "stockInventoryID": 84, "name": "nisi" },
        { "locationID": 4, "stockInventoryID": 11, "name": "quam suspendisse" },
        { "locationID": 6, "stockInventoryID": 82, "name": "semper interdum" },
        { "locationID": 17, "stockInventoryID": 71, "name": "a" },
        { "locationID": 23, "stockInventoryID": 41, "name": "urna pretium" },
        { "locationID": 18, "stockInventoryID": 12, "name": "sapien" },
        { "locationID": 5, "stockInventoryID": 25, "name": "felis fusce" },
        { "locationID": 15, "stockInventoryID": 48, "name": "lorem" },
        { "locationID": 15, "stockInventoryID": 9, "name": "platea dictumst" },
        { "locationID": 24, "stockInventoryID": 11, "name": "adipiscing lorem" },
        { "locationID": 9, "stockInventoryID": 61, "name": "sapien" },
        { "locationID": 21, "stockInventoryID": 36, "name": "habitasse platea" },
        { "locationID": 13, "stockInventoryID": 86, "name": "est" },
        { "locationID": 10, "stockInventoryID": 96, "name": "ac diam" },
        { "locationID": 19, "stockInventoryID": 9, "name": "pede libero" },
        { "locationID": 23, "stockInventoryID": 53, "name": "est" },
        { "locationID": 3, "stockInventoryID": 54, "name": "sapien dignissim" },
        { "locationID": 2, "stockInventoryID": 35, "name": "turpis" },
        { "locationID": 3, "stockInventoryID": 81, "name": "volutpat erat" },
        { "locationID": 7, "stockInventoryID": 76, "name": "leo" },
        { "locationID": 2, "stockInventoryID": 81, "name": "volutpat" },
        { "locationID": 16, "stockInventoryID": 23, "name": "erat fermentum" },
        { "locationID": 19, "stockInventoryID": 93, "name": "quis" },
        { "locationID": 22, "stockInventoryID": 31, "name": "elementum in" },
        { "locationID": 21, "stockInventoryID": 57, "name": "id massa" },
        { "locationID": 22, "stockInventoryID": 43, "name": "semper sapien" },
        { "locationID": 16, "stockInventoryID": 25, "name": "quis" },
        { "locationID": 13, "stockInventoryID": 29, "name": "risus dapibus" },
        { "locationID": 18, "stockInventoryID": 65, "name": "pede libero" },
        { "locationID": 16, "stockInventoryID": 83, "name": "vestibulum" },
        { "locationID": 19, "stockInventoryID": 89, "name": "nec" },
        { "locationID": 26, "stockInventoryID": 70, "name": "dapibus" },
        { "locationID": 16, "stockInventoryID": 62, "name": "sit" },
        { "locationID": 27, "stockInventoryID": 23, "name": "sit" },
        { "locationID": 19, "stockInventoryID": 100, "name": "aliquam non" },
        { "locationID": 26, "stockInventoryID": 25, "name": "pharetra magna" },
        { "locationID": 1, "stockInventoryID": 90, "name": "sodales scelerisque" },
        { "locationID": 24, "stockInventoryID": 34, "name": "sed interdum" },
        { "locationID": 16, "stockInventoryID": 82, "name": "pede justo" },
        { "locationID": 11, "stockInventoryID": 10, "name": "dolor" },
        { "locationID": 23, "stockInventoryID": 93, "name": "ut odio" },
        { "locationID": 16, "stockInventoryID": 69, "name": "parturient" },
        { "locationID": 27, "stockInventoryID": 44, "name": "nam congue" },
        { "locationID": 10, "stockInventoryID": 14, "name": "scelerisque" },
        { "locationID": 22, "stockInventoryID": 44, "name": "ut suscipit" },
        { "locationID": 5, "stockInventoryID": 98, "name": "eu" },
        { "locationID": 7, "stockInventoryID": 60, "name": "cursus vestibulum" },
        { "locationID": 4, "stockInventoryID": 4, "name": "velit eu" },
        { "locationID": 26, "stockInventoryID": 87, "name": "nisi" },
        { "locationID": 3, "stockInventoryID": 20, "name": "sapien cum" },
        { "locationID": 13, "stockInventoryID": 81, "name": "sapien cursus" },
        { "locationID": 12, "stockInventoryID": 82, "name": "vivamus vel" },
        { "locationID": 14, "stockInventoryID": 77, "name": "nam dui" },
        { "locationID": 10, "stockInventoryID": 28, "name": "sed" },
        { "locationID": 10, "stockInventoryID": 21, "name": "scelerisque" },
        { "locationID": 18, "stockInventoryID": 50, "name": "sem fusce" },
        { "locationID": 2, "stockInventoryID": 58, "name": "luctus" },
        { "locationID": 26, "stockInventoryID": 41, "name": "nulla" },
        { "locationID": 14, "stockInventoryID": 96, "name": "congue" },
        { "locationID": 24, "stockInventoryID": 9, "name": "ut massa" },
        { "locationID": 16, "stockInventoryID": 88, "name": "lectus" },
        { "locationID": 7, "stockInventoryID": 35, "name": "morbi" },
        { "locationID": 12, "stockInventoryID": 95, "name": "hac" },
        { "locationID": 24, "stockInventoryID": 15, "name": "hac habitasse" },
        { "locationID": 8, "stockInventoryID": 68, "name": "est lacinia" },
        { "locationID": 18, "stockInventoryID": 38, "name": "nulla facilisi" },
        { "locationID": 10, "stockInventoryID": 16, "name": "sem fusce" },
        { "locationID": 2, "stockInventoryID": 67, "name": "nulla" },
        { "locationID": 19, "stockInventoryID": 21, "name": "est quam" },
        { "locationID": 21, "stockInventoryID": 88, "name": "vel" },
        { "locationID": 18, "stockInventoryID": 65, "name": "velit donec" },
        { "locationID": 11, "stockInventoryID": 42, "name": "sociis" },
        { "locationID": 5, "stockInventoryID": 35, "name": "quis lectus" },
        { "locationID": 11, "stockInventoryID": 93, "name": "curabitur" },
        { "locationID": 19, "stockInventoryID": 87, "name": "auctor" },
        { "locationID": 4, "stockInventoryID": 7, "name": "lacus" },
        { "locationID": 11, "stockInventoryID": 87, "name": "mauris" },
        { "locationID": 14, "stockInventoryID": 42, "name": "ac" },
        { "locationID": 24, "stockInventoryID": 89, "name": "at nibh" },
        { "locationID": 9, "stockInventoryID": 69, "name": "varius" },
        { "locationID": 4, "stockInventoryID": 8, "name": "maecenas" },
        { "locationID": 23, "stockInventoryID": 23, "name": "ligula in" },
        { "locationID": 9, "stockInventoryID": 69, "name": "dapibus nulla" },
        { "locationID": 26, "stockInventoryID": 54, "name": "accumsan" },
        { "locationID": 4, "stockInventoryID": 97, "name": "odio" },
        { "locationID": 15, "stockInventoryID": 78, "name": "tincidunt" },
        { "locationID": 18, "stockInventoryID": 59, "name": "lobortis convallis" },
        { "locationID": 14, "stockInventoryID": 87, "name": "non" },
        { "locationID": 6, "stockInventoryID": 87, "name": "porttitor" },
        { "locationID": 4, "stockInventoryID": 25, "name": "dapibus" },
        { "locationID": 6, "stockInventoryID": 77, "name": "vitae" },
        { "locationID": 27, "stockInventoryID": 72, "name": "sit" },
        { "locationID": 11, "stockInventoryID": 82, "name": "quis justo" },
        { "locationID": 21, "stockInventoryID": 60, "name": "pellentesque" },
        { "locationID": 8, "stockInventoryID": 63, "name": "molestie lorem" },
        { "locationID": 11, "stockInventoryID": 27, "name": "duis faucibus" },
        { "locationID": 12, "stockInventoryID": 80, "name": "vestibulum rutrum" },
        { "locationID": 23, "stockInventoryID": 47, "name": "potenti nullam" },
        { "locationID": 13, "stockInventoryID": 79, "name": "mattis" },
        { "locationID": 23, "stockInventoryID": 35, "name": "morbi sem" },
        { "locationID": 20, "stockInventoryID": 97, "name": "maecenas rhoncus" },
        { "locationID": 23, "stockInventoryID": 87, "name": "cubilia" },
        { "locationID": 2, "stockInventoryID": 23, "name": "eu massa" },
        { "locationID": 6, "stockInventoryID": 2, "name": "vestibulum" },
        { "locationID": 27, "stockInventoryID": 84, "name": "sollicitudin" },
        { "locationID": 27, "stockInventoryID": 38, "name": "ligula" },
        { "locationID": 12, "stockInventoryID": 14, "name": "semper sapien" },
        { "locationID": 6, "stockInventoryID": 71, "name": "augue a" },
        { "locationID": 10, "stockInventoryID": 26, "name": "ac" },
        { "locationID": 25, "stockInventoryID": 34, "name": "consequat varius" },
        { "locationID": 8, "stockInventoryID": 15, "name": "semper interdum" },
        { "locationID": 5, "stockInventoryID": 31, "name": "eu" },
        { "locationID": 17, "stockInventoryID": 27, "name": "phasellus in" },
        { "locationID": 14, "stockInventoryID": 7, "name": "dis parturient" },
        { "locationID": 8, "stockInventoryID": 78, "name": "eget semper" },
        { "locationID": 14, "stockInventoryID": 8, "name": "integer" },
        { "locationID": 2, "stockInventoryID": 30, "name": "porttitor" },
        { "locationID": 27, "stockInventoryID": 14, "name": "vestibulum ante" },
        { "locationID": 24, "stockInventoryID": 60, "name": "ullamcorper" },
        { "locationID": 4, "stockInventoryID": 49, "name": "morbi non" },
        { "locationID": 5, "stockInventoryID": 43, "name": "in quis" },
        { "locationID": 2, "stockInventoryID": 78, "name": "amet consectetuer" },
        { "locationID": 20, "stockInventoryID": 12, "name": "amet eleifend" },
        { "locationID": 19, "stockInventoryID": 11, "name": "sagittis nam" },
        { "locationID": 18, "stockInventoryID": 2, "name": "tempus sit" },
        { "locationID": 7, "stockInventoryID": 68, "name": "ligula" },
        { "locationID": 15, "stockInventoryID": 38, "name": "vestibulum" },
        { "locationID": 16, "stockInventoryID": 26, "name": "ante" },
        { "locationID": 7, "stockInventoryID": 38, "name": "non" },
        { "locationID": 19, "stockInventoryID": 25, "name": "nunc viverra" },
        { "locationID": 20, "stockInventoryID": 64, "name": "fermentum" },
        { "locationID": 3, "stockInventoryID": 41, "name": "sed" },
        { "locationID": 22, "stockInventoryID": 52, "name": "penatibus" },
        { "locationID": 16, "stockInventoryID": 26, "name": "pretium" },
        { "locationID": 26, "stockInventoryID": 24, "name": "molestie" },
        { "locationID": 26, "stockInventoryID": 83, "name": "vivamus" },
        { "locationID": 21, "stockInventoryID": 97, "name": "suspendisse" },
        { "locationID": 3, "stockInventoryID": 68, "name": "ante vivamus" },
        { "locationID": 8, "stockInventoryID": 36, "name": "sociis natoque" },
        { "locationID": 1, "stockInventoryID": 16, "name": "sed" },
        { "locationID": 6, "stockInventoryID": 70, "name": "diam vitae" },
        { "locationID": 11, "stockInventoryID": 53, "name": "nulla" },
        { "locationID": 10, "stockInventoryID": 4, "name": "mattis egestas" },
        { "locationID": 11, "stockInventoryID": 38, "name": "nullam orci" },
        { "locationID": 6, "stockInventoryID": 44, "name": "ac" },
        { "locationID": 16, "stockInventoryID": 33, "name": "proin" },
        { "locationID": 25, "stockInventoryID": 97, "name": "vestibulum ante" },
        { "locationID": 11, "stockInventoryID": 45, "name": "eget" },
        { "locationID": 15, "stockInventoryID": 10, "name": "vestibulum" },
        { "locationID": 11, "stockInventoryID": 96, "name": "libero convallis" },
        { "locationID": 10, "stockInventoryID": 43, "name": "in" },
        { "locationID": 12, "stockInventoryID": 44, "name": "justo in" },
        { "locationID": 23, "stockInventoryID": 42, "name": "duis faucibus" },
        { "locationID": 12, "stockInventoryID": 34, "name": "bibendum" },
        { "locationID": 9, "stockInventoryID": 81, "name": "aliquam" },
        { "locationID": 22, "stockInventoryID": 71, "name": "ac lobortis" },
        { "locationID": 20, "stockInventoryID": 23, "name": "dapibus at" },
        { "locationID": 19, "stockInventoryID": 88, "name": "bibendum" },
        { "locationID": 3, "stockInventoryID": 80, "name": "et" },
        { "locationID": 7, "stockInventoryID": 52, "name": "nam" },
        { "locationID": 5, "stockInventoryID": 56, "name": "arcu" },
        { "locationID": 24, "stockInventoryID": 56, "name": "tempus" },
        { "locationID": 19, "stockInventoryID": 92, "name": "habitasse" },
        { "locationID": 7, "stockInventoryID": 62, "name": "vitae" },
        { "locationID": 5, "stockInventoryID": 86, "name": "molestie hendrerit" },
        { "locationID": 6, "stockInventoryID": 64, "name": "vitae ipsum" },
        { "locationID": 22, "stockInventoryID": 61, "name": "rutrum" },
        { "locationID": 22, "stockInventoryID": 7, "name": "cubilia curae" },
        { "locationID": 1, "stockInventoryID": 13, "name": "ac enim" },
        { "locationID": 25, "stockInventoryID": 22, "name": "velit" },
        { "locationID": 27, "stockInventoryID": 34, "name": "ultrices" },
        { "locationID": 3, "stockInventoryID": 82, "name": "lacus morbi" },
        { "locationID": 9, "stockInventoryID": 1, "name": "elementum" },
        { "locationID": 26, "stockInventoryID": 27, "name": "felis" },
        { "locationID": 23, "stockInventoryID": 49, "name": "nunc nisl" },
        { "locationID": 5, "stockInventoryID": 53, "name": "mus" },
        { "locationID": 22, "stockInventoryID": 94, "name": "erat" },
        { "locationID": 15, "stockInventoryID": 70, "name": "mattis egestas" },
        { "locationID": 16, "stockInventoryID": 63, "name": "quam" },
        { "locationID": 17, "stockInventoryID": 56, "name": "ipsum" },
        { "locationID": 23, "stockInventoryID": 18, "name": "lorem ipsum" },
        { "locationID": 2, "stockInventoryID": 10, "name": "consequat dui" },
        { "locationID": 9, "stockInventoryID": 61, "name": "sapien cum" },
        { "locationID": 23, "stockInventoryID": 55, "name": "a ipsum" },
        { "locationID": 15, "stockInventoryID": 78, "name": "id turpis" },
        { "locationID": 22, "stockInventoryID": 62, "name": "lectus aliquam" },
        { "locationID": 25, "stockInventoryID": 26, "name": "ipsum" },
        { "locationID": 25, "stockInventoryID": 31, "name": "nullam" },
        { "locationID": 16, "stockInventoryID": 45, "name": "sit" },
        { "locationID": 20, "stockInventoryID": 72, "name": "faucibus orci" },
        { "locationID": 26, "stockInventoryID": 62, "name": "duis faucibus" },
        { "locationID": 22, "stockInventoryID": 21, "name": "consequat nulla" },
        { "locationID": 6, "stockInventoryID": 12, "name": "velit" },
        { "locationID": 27, "stockInventoryID": 85, "name": "amet nunc" },
        { "locationID": 3, "stockInventoryID": 87, "name": "penatibus et" },
        { "locationID": 27, "stockInventoryID": 49, "name": "magna at" },
        { "locationID": 9, "stockInventoryID": 60, "name": "sapien" },
        { "locationID": 2, "stockInventoryID": 46, "name": "proin" },
        { "locationID": 15, "stockInventoryID": 99, "name": "consequat metus" },
        { "locationID": 13, "stockInventoryID": 42, "name": "odio odio" },
        { "locationID": 18, "stockInventoryID": 24, "name": "mi in" },
        { "locationID": 7, "stockInventoryID": 54, "name": "non" },
        { "locationID": 5, "stockInventoryID": 7, "name": "pellentesque" },
        { "locationID": 7, "stockInventoryID": 56, "name": "ac nibh" },
        { "locationID": 2, "stockInventoryID": 15, "name": "lorem" },
        { "locationID": 24, "stockInventoryID": 78, "name": "nisi" },
        { "locationID": 6, "stockInventoryID": 76, "name": "in" },
        { "locationID": 16, "stockInventoryID": 66, "name": "hac" },
        { "locationID": 19, "stockInventoryID": 11, "name": "habitasse platea" },
        { "locationID": 26, "stockInventoryID": 90, "name": "erat" },
        { "locationID": 27, "stockInventoryID": 58, "name": "lectus pellentesque" },
        { "locationID": 17, "stockInventoryID": 35, "name": "nullam" },
        { "locationID": 20, "stockInventoryID": 84, "name": "proin" },
        { "locationID": 24, "stockInventoryID": 48, "name": "nibh quisque" },
        { "locationID": 18, "stockInventoryID": 24, "name": "nulla" },
        { "locationID": 22, "stockInventoryID": 93, "name": "pharetra" },
        { "locationID": 10, "stockInventoryID": 77, "name": "praesent" },
        { "locationID": 12, "stockInventoryID": 10, "name": "orci" },
        { "locationID": 23, "stockInventoryID": 64, "name": "vulputate nonummy" },
        { "locationID": 9, "stockInventoryID": 85, "name": "integer" },
        { "locationID": 10, "stockInventoryID": 78, "name": "vitae" },
        { "locationID": 9, "stockInventoryID": 64, "name": "sed vestibulum" },
        { "locationID": 22, "stockInventoryID": 59, "name": "suscipit" },
        { "locationID": 17, "stockInventoryID": 9, "name": "urna" },
        { "locationID": 19, "stockInventoryID": 52, "name": "elit ac" },
        { "locationID": 7, "stockInventoryID": 16, "name": "eget massa" },
        { "locationID": 1, "stockInventoryID": 1, "name": "rutrum" },
        { "locationID": 11, "stockInventoryID": 62, "name": "vestibulum" },
        { "locationID": 2, "stockInventoryID": 90, "name": "eget tincidunt" },
        { "locationID": 19, "stockInventoryID": 16, "name": "convallis" },
        { "locationID": 13, "stockInventoryID": 46, "name": "maecenas pulvinar" },
        { "locationID": 19, "stockInventoryID": 73, "name": "pulvinar" },
        { "locationID": 4, "stockInventoryID": 93, "name": "pellentesque" },
        { "locationID": 25, "stockInventoryID": 92, "name": "interdum" },
        { "locationID": 11, "stockInventoryID": 35, "name": "consequat" },
        { "locationID": 7, "stockInventoryID": 35, "name": "egestas" },
        { "locationID": 8, "stockInventoryID": 40, "name": "tortor quis" },
        { "locationID": 15, "stockInventoryID": 4, "name": "suspendisse" },
        { "locationID": 3, "stockInventoryID": 60, "name": "cras non" },
        { "locationID": 25, "stockInventoryID": 83, "name": "lorem ipsum" },
        { "locationID": 6, "stockInventoryID": 81, "name": "pede justo" },
        { "locationID": 27, "stockInventoryID": 90, "name": "mattis egestas" },
        { "locationID": 4, "stockInventoryID": 89, "name": "congue diam" },
        { "locationID": 19, "stockInventoryID": 48, "name": "potenti" },
        { "locationID": 12, "stockInventoryID": 45, "name": "turpis" },
        { "locationID": 27, "stockInventoryID": 35, "name": "platea dictumst" },
        { "locationID": 19, "stockInventoryID": 87, "name": "orci" },
        { "locationID": 20, "stockInventoryID": 98, "name": "convallis" },
        { "locationID": 26, "stockInventoryID": 31, "name": "sodales sed" },
        { "locationID": 3, "stockInventoryID": 59, "name": "mauris enim" },
        { "locationID": 27, "stockInventoryID": 90, "name": "ante ipsum" },
        { "locationID": 21, "stockInventoryID": 46, "name": "erat nulla" },
        { "locationID": 5, "stockInventoryID": 37, "name": "nunc nisl" },
        { "locationID": 18, "stockInventoryID": 31, "name": "platea" },
        { "locationID": 8, "stockInventoryID": 18, "name": "dapibus augue" },
        { "locationID": 25, "stockInventoryID": 21, "name": "pede" },
        { "locationID": 18, "stockInventoryID": 6, "name": "convallis nunc" },
        { "locationID": 20, "stockInventoryID": 29, "name": "turpis" },
        { "locationID": 15, "stockInventoryID": 48, "name": "cursus" },
        { "locationID": 21, "stockInventoryID": 30, "name": "ante" },
        { "locationID": 3, "stockInventoryID": 58, "name": "primis in" },
        { "locationID": 26, "stockInventoryID": 35, "name": "cursus" },
        { "locationID": 2, "stockInventoryID": 30, "name": "ac" },
        { "locationID": 10, "stockInventoryID": 39, "name": "dapibus" },
        { "locationID": 16, "stockInventoryID": 9, "name": "lorem vitae" },
        { "locationID": 6, "stockInventoryID": 71, "name": "in est" },
        { "locationID": 6, "stockInventoryID": 21, "name": "ut nunc" },
        { "locationID": 21, "stockInventoryID": 75, "name": "lacus curabitur" },
        { "locationID": 18, "stockInventoryID": 7, "name": "sapien sapien" },
        { "locationID": 17, "stockInventoryID": 12, "name": "sed magna" },
        { "locationID": 21, "stockInventoryID": 79, "name": "dictumst" },
        { "locationID": 12, "stockInventoryID": 99, "name": "ornare consequat" },
        { "locationID": 23, "stockInventoryID": 71, "name": "hac" },
        { "locationID": 6, "stockInventoryID": 80, "name": "amet eros" },
        { "locationID": 14, "stockInventoryID": 59, "name": "in felis" },
        { "locationID": 6, "stockInventoryID": 67, "name": "eu tincidunt" },
        { "locationID": 23, "stockInventoryID": 93, "name": "donec" },
        { "locationID": 7, "stockInventoryID": 21, "name": "donec" },
        { "locationID": 5, "stockInventoryID": 99, "name": "orci" },
        { "locationID": 27, "stockInventoryID": 10, "name": "donec pharetra" },
        { "locationID": 22, "stockInventoryID": 44, "name": "id" },
        { "locationID": 19, "stockInventoryID": 94, "name": "volutpat eleifend" },
        { "locationID": 8, "stockInventoryID": 68, "name": "massa" },
        { "locationID": 22, "stockInventoryID": 12, "name": "molestie lorem" },
        { "locationID": 9, "stockInventoryID": 74, "name": "elementum" },
        { "locationID": 16, "stockInventoryID": 31, "name": "posuere" },
        { "locationID": 24, "stockInventoryID": 91, "name": "cursus vestibulum" },
        { "locationID": 14, "stockInventoryID": 28, "name": "cubilia curae" },
        { "locationID": 22, "stockInventoryID": 75, "name": "id justo" },
        { "locationID": 9, "stockInventoryID": 94, "name": "in eleifend" },
        { "locationID": 3, "stockInventoryID": 66, "name": "posuere" },
        { "locationID": 19, "stockInventoryID": 57, "name": "justo in" },
        { "locationID": 10, "stockInventoryID": 16, "name": "ultrices mattis" },
        { "locationID": 15, "stockInventoryID": 55, "name": "luctus et" },
        { "locationID": 7, "stockInventoryID": 62, "name": "tellus nulla" },
        { "locationID": 9, "stockInventoryID": 78, "name": "posuere nonummy" },
        { "locationID": 27, "stockInventoryID": 60, "name": "aenean" },
        { "locationID": 24, "stockInventoryID": 94, "name": "vestibulum" },
        { "locationID": 20, "stockInventoryID": 35, "name": "aliquam" },
        { "locationID": 12, "stockInventoryID": 38, "name": "pede" },
        { "locationID": 8, "stockInventoryID": 36, "name": "ut" },
        { "locationID": 11, "stockInventoryID": 93, "name": "amet sem" },
        { "locationID": 9, "stockInventoryID": 16, "name": "vestibulum" },
        { "locationID": 19, "stockInventoryID": 46, "name": "sed interdum" },
        { "locationID": 9, "stockInventoryID": 37, "name": "consequat" },
        { "locationID": 16, "stockInventoryID": 41, "name": "magna vestibulum" },
        { "locationID": 11, "stockInventoryID": 70, "name": "ipsum" },
        { "locationID": 22, "stockInventoryID": 92, "name": "cras mi" },
        { "locationID": 2, "stockInventoryID": 68, "name": "nullam" },
        { "locationID": 20, "stockInventoryID": 73, "name": "vel augue" },
        { "locationID": 24, "stockInventoryID": 91, "name": "proin" },
        { "locationID": 19, "stockInventoryID": 58, "name": "ultrices" },
        { "locationID": 23, "stockInventoryID": 16, "name": "leo maecenas" },
        { "locationID": 18, "stockInventoryID": 85, "name": "turpis adipiscing" },
        { "locationID": 9, "stockInventoryID": 69, "name": "eros" }]
      );
    });
};
