
exports.seed = function (knex, Promise) {
    // Deletes ALL existing entries
    return knex('Permission').del()
        .then(function () {
            // Inserts seed entries
            return knex('Permission').insert(
                [{ "name": "habitasse platea" },
                { "name": "sapien sapien" },
                { "name": "volutpat" },
                { "name": "eget congue eget" },
                { "name": "vestibulum aliquet ultrices" },
                { "name": "at ipsum ac" },
                { "name": "ante vestibulum" },
                { "name": "sapien varius ut" },
                { "name": "fusce consequat nulla" },
                { "name": "eu pede" },
                { "name": "enim sit amet" },
                { "name": "fermentum donec ut" },
                { "name": "nascetur ridiculus" },
                { "name": "commodo placerat" },
                { "name": "viverra" },
                { "name": "porta" },
                { "name": "vestibulum ante ipsum" },
                { "name": "non interdum" },
                { "name": "magna vulputate luctus" },
                { "name": "molestie lorem quisque" },
                { "name": "sapien a" },
                { "name": "montes nascetur" },
                { "name": "ligula" },
                { "name": "ultrices phasellus" },
                { "name": "rutrum" },
                { "name": "at" },
                { "name": "pulvinar nulla pede" },
                { "name": "nulla" },
                { "name": "tincidunt eu" },
                { "name": "mi pede" },
                { "name": "vivamus tortor" },
                { "name": "semper porta volutpat" },
                { "name": "ac nibh" },
                { "name": "in faucibus orci" },
                { "name": "curae" },
                { "name": "vitae" },
                { "name": "ut massa" },
                { "name": "vulputate luctus" },
                { "name": "rhoncus aliquam lacus" },
                { "name": "in" },
                { "name": "hac" },
                { "name": "elementum" },
                { "name": "et" },
                { "name": "a feugiat et" },
                { "name": "consequat morbi a" },
                { "name": "lorem" },
                { "name": "morbi non lectus" },
                { "name": "commodo placerat" },
                { "name": "nisi at nibh" },
                { "name": "ac diam" },
                { "name": "pede ullamcorper" },
                { "name": "nisi at nibh" },
                { "name": "donec vitae nisi" },
                { "name": "volutpat erat" },
                { "name": "blandit nam nulla" },
                { "name": "mauris" },
                { "name": "praesent" },
                { "name": "cubilia curae" },
                { "name": "purus" },
                { "name": "et eros vestibulum" },
                { "name": "accumsan" },
                { "name": "at" },
                { "name": "quis" },
                { "name": "massa" },
                { "name": "bibendum" },
                { "name": "tincidunt lacus at" },
                { "name": "odio" },
                { "name": "odio consequat varius" },
                { "name": "nibh fusce" },
                { "name": "orci" },
                { "name": "faucibus orci luctus" },
                { "name": "ipsum dolor sit" },
                { "name": "arcu" },
                { "name": "lectus" },
                { "name": "lorem vitae" },
                { "name": "quisque" },
                { "name": "platea" },
                { "name": "amet erat nulla" },
                { "name": "purus" },
                { "name": "consequat dui" },
                { "name": "donec" },
                { "name": "non" },
                { "name": "aenean sit" },
                { "name": "non quam" },
                { "name": "erat nulla tempus" },
                { "name": "eget" },
                { "name": "erat eros" },
                { "name": "tristique" },
                { "name": "ut suscipit" },
                { "name": "dis parturient montes" },
                { "name": "eget" },
                { "name": "mi" },
                { "name": "pellentesque volutpat dui" },
                { "name": "facilisi cras non" },
                { "name": "etiam" },
                { "name": "nulla dapibus" },
                { "name": "vel accumsan" },
                { "name": "posuere felis sed" },
                { "name": "duis bibendum felis" },
                { "name": "at dolor quis" }]);
        });
};
